### ISSUE TITLE
New Task: Visual Regression testing

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-grunt#10]
Add _grunt-screenshot_ or similar for generating JPG images of desktop, tablet and mobile views to help with final polish and QA. This would be a standalone task not bundled into the `default` stack.

**Comment by mwtsn** [comment]
@davetgreen would you be able to say which URLs it grabs the screenshot(s) from?

Does this work with Casper or similar?

**Comment by davetgreen** [comment]
@mwtsn yeah that's kinda mandatory from the R&D I've done. I think you can point to a root URL if you want, but we can definitely pass it a manifest of URLs.

It's Casper/PhantomJS used pretty widely I think.
