### ISSUE TITLE
New Task: Accessibility testing

### ISSUE THREAD

**Issue by davetgreen** [kapow-wp/kapow-grunt#14]
We need to investigate building a11y testing into our grunt stack, as an alternative to using Total Validator Pro. TVP is still a fantastic tool, but it comes with the cost overhead and is another application we need to use.

Consider:

https://github.com/yargalot/grunt-accessibility
https://github.com/cbaigorri/grunt-pa11y
https://github.com/globant-ui/arialinter

Also consider looking into the BETA plugin available for the Tenon.io SaaS a11y testing service.

**Comment by mwtsn** [comment]
@davetgreen I still think TVP will be useful as a manual check, but preventing a commit unless it passes accessibility is definitely +1 :)
